# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r requirements.txt
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
        ls dist/*
    - name: Save wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist/wntr*.whl

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Download wheel
      uses: actions/download-artifact@v2
      with:
        name: wheel
    - run: dir
    - name: Install wntr
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install wheel/wntr*.whl
