# This is a basic workflow to help you get started with Actions

name: CI Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test-nix:
    name: "*nix Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda config --set always_yes yes --set changeps1 no
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        conda install -c conda-forge glpk
        pip install chama coveralls
        python setup.py develop
    - run: conda --version
    - run: python --version
    - name: Run Tests
      run: |
        nosetests -v --nologcapture --with-coverage --with-doctest --doctest-extension=.rst --cover-package=wntr documentation/*.rst wntr
    - name: Upload Coverage
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: ${{ matrix.os }} py${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
  test-windows:
    name: Win Tests
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls
        python setup.py develop
    - name: Run Tests
      run: nosetests -v --nologcapture --with-coverage --with-doctest --doctest-extension=.rst --exclude=test_examples --traverse-namespace --cover-package=wntr wntr
    - name: Upload Coverage
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COVERALLS_FLAG_NAME: windows-latest py${{ matrix.python-version }}
        COVERALLS_PARALLEL: true
  finish:
    name: Finish Coveralls
    needs: [test-nix, test-windows]
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
