# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: quick-check

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade coverage pytest
    # Build extensions are accessible from package level, similar to python setup.py build_ext --inplace
    - name: Install package for development
      run: |
        python setup.py develop
    - name: Run tests and coverage
      run: |
        coverage run -m pytest --doctest-modules wntr
        coverage report --fail-under=70        
    # pytest --doctest-modules wntr/tests/test_times.py
    # nose -v --nologcapture --with-doctest --exclude=test_examples --with-coverage --cover-package=wntr --cover-min-percentage=70 wntr
