# This workflow will build wheels and upload them to pypi

name: release

on:
  push:
    #tags:
    #  - '*'
    #branches:
    #  - main

jobs:

  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [windows-2019, macOS-11, ubuntu-20.04] 
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *-musllinux*"
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: build the sdist
        run: |
          python -m pip install --upgrade build
          python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
