# This workflow will build wheels and upload them to pypi

name: release

on:
  push:
    #tags:
    #  - '*'
    #branches:
    #  - main

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #python-version: ['3.7', '3.8', '3.9', '3.10']
        os: [windows-latest, macOS-latest, ubuntu-latest] 
    steps:
    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
    - uses: actions/upload-artifact@v3
      with:
        path: ./wheel_dir/*.whl
