# This is a basic workflow to help you get started with Actions

name: examples

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda config --set always_yes yes --set changeps1 no
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        conda install -c conda-forge glpk
        pip install chama
        python setup.py develop
    - name: Run Tests
      run: |
        nosetests -v --nologcapture --with-doctest --doctest-extension=.rst documentation/*.rst wntr
